.TH CSVREAD 1 "8 October 2018"
.SH NAME
csvread \- print csv rows in a human\-readable format
.SH SYNOPSIS
\fBcsvread\fP [\-h] [\-x] [\-d \fIDELIM\fP] [\-l \fILIB\fP] [\-p \fIPATH\fP] [\fIFILE\fP [\fIFILE\fP ...]]
.SH DESCRIPTION
\fBcsvread\fP displays a comma\-separated value (csv) file \fIFILE\fP in a more
readable format.  It prints one value per line, prefixed by the header that
corresponds to the value's column, where the header is the first row of the
file and is not printed separately.  An empty line is printed between the last
value of each row and the first value of the next row, serving as a record
separator.

This purpose of this layout is to make it clear which values in the file
correspond to which headers.  The layout can also be used to grep for a
specific column or columns.  Piping its output to cgrep(1), the layout can
look for records containing certain values in certain columns.
.SS Options
.TP
\fB-h\fP, \fB--help\fP
Output a usage message and exit.
.TP
\fB-x\fP, \fB--no-header\fP
The file contains no header.  The values are numbered by their column positions
instead.
.TP
\fB-d\fP \fIDELIM\fP, \fB--delim\fP=\fIDELIM\fP
Use \fIDELIM\fP as the value delimiter instead of a comma.
.TP
\fB-l\fP \fILIB\fP, \fB--lib\fP=\fILIB\fP
Use the plugin library \fILIB\fP to preprocess header(s) and/or values before
display.  Useful for enriching symbols in values or headers with a description
of their meaning.  \fILIB\fP may be a full path to the library without the .py
suffix, or it may just be the library name in which case the appropriate paths
are searched.
.TP
\fB-p\fP \fIPATH\fP, \fB--path\fP=\fIPATH\fP
Search for the plugin library in \fIPATH\fP.
.SS Variables
.TP
\fBPYTHONPATH\fP
A colon-separated list of directories in which the plugin library is searched.
.SH "SEE ALSO"
cgrep(1)
